### ISSUE TITLE
browser testing needed

### ISSUE THREAD

**Issue by riedelwerk** [opendata-stuttgart/feinstaub-map#1]
please test all browsers:

Chrome will work
Firefox will work
Safari - you can see no sensors, map will be seen
Windows Internet Explorer - not tested

**Comment by rashfael** [comment]
Biggest bleeding edges:
- [Fetch](http://caniuse.com/#feat=fetch)
- [Flexbox](http://caniuse.com/#feat=flexbox)

**Comment by rashfael** [comment]
Thanks to @ubahnverleih Safari should work now.
The added fetch polyfill should also fix IE.

If someone currently wants to invest time in setting up automated test environments we could support a wide range of devices, otherwise we have to rely on bug reports and fixes.

Support for Chrome and Firefox newest Version-1 is easy.
Supporting popular and up-to-date mobile Browsers is doable.
IE Edge should just work™ (with the fetch polyfill), perhaps with some quirks.
