### ISSUE TITLE
improving the maps, more cooperation with openSenseMap (merging both projects?)

### ISSUE THREAD

**Issue by WiliTest** [opendata-stuttgart/feinstaub-map#69]
Just a feedback: the current map doesn't explain the data shown on its map is: does it show the last reading or the average? And how to get an idea of the week/month data? It doesn't show any graph, the users can't even add some comments on their sensor, (and, optional), a picture (openSenseMap does). And the worst part is that it's not automatic: you need to wait weeks (months?) before someone registers the sensor on the map. 

It would be great to work in collaboration with openSenseMap, the combination of the two maps would provide a decent map of air pollution (and much more). 

It's also a pity that openSenseMap gets so few data from your sensor. I already talked about it here: https://github.com/sensebox/openSenseMap/issues/290 

Thanks for your awesome work!

**Comment by ricki-z** [comment]
Short answer:
We don't force anybody to take part in our project. There is also a sensor for the opensensemap project that you could buy and use.

Long answer:
Have you ever clicked on one of the heaxagons on the map (like most users do)? If you do this you can get also an explanation of what is shown on the map. At the moment in german only, but a new version of the map is work in progress (see last paragraph). And you can see two graphs, one for the last 24 hours and one with the floating 24 hour average for the last 7 days.
Comments are 'critical', some people might use this to advertise product, companies or political opinions.
And we are working on an automatic registration. This should go online in the next few weeks.
Yes, at the moment we are some days behind with registrations. But have you looked in your spam folder if you may have received the confimation? Especially GMail accounts seem to sort out our mails as spam.

To your comment at sensebox/openSenseMap#290:
Our data is open. We publish the data of the last 5 minutes as a JSON file, that can be accessed by everyone (the location information in this file and all other published data is rounded to 1/500th degrees). And all data is archived at http://archive.luftdaten.info/ once per day. There are some other possibilities to access data mentioned in our FAQ and here in our Github account (https://github.com/opendata-stuttgart/meta/wiki)

If you are unhappy with our mapor the one at opensensemap.org: You can build your own, like other people have done. One example is https://influencair.be/map-brussels/ , it seems like they can access our data ...

Luftdaten.info is organized by citizens in their leisure time while opensensemap ist getting fundings from federal organizations (actually Federal Ministry of education and research, www.bmbf.de).
Because of this our resources are more limited than those of opensensemap and we can't implement every desired feature at all or as fast as a funded project.

**Comment by WiliTest** [comment]
Thank you very much for taken the time your reply!

Thanks to you, I just discovered I the graphs by clicking on the "+" sign (shame on me!) It's impressive you have manage to beat opensensemap without funding!

> Comments are 'critical', some people might use this to advertise product, companies or political opinions.
I don't believe in this one (since I value the "who care?" and "freespeech" _above/despite all_). But I understand your point.

I'm (super) glad we could access the data, I'll look at it.

ps: I apologize, my post was too short/direct to show my appreciation of the work you have done (I'm fully aware of what the  "is organized by citizens in their leisure time" means, and the sacrifices which goes with). I (really!) find your project and work/talent you offer awesome (and even more!).
